### ISSUE TITLE
model/ensemble_model.py is not found

### ISSUE THREAD

**Issue by usaribbon** [pcyin/dire#2]
Hello,  I'm trying to run DIRE.
I found that `model/ensemble_model.py` seems to be missing.
This causes an error when I execute `exe.py`.
Could you add `model/ensemble_model.py` on the repo?

```
...
from model.simple_decoder import SimpleDecoder
from model.graph_encoder import GraphASTEncoder
from model.gnn import AdjacencyList, GatedGraphNeuralNetwork
from model.model import RenamingModel
from utils import nn_util, util
from utils.ast import AbstractSyntaxTree
from utils.dataset import Dataset, Example
ain": { "evaluate_every_nepoch": 5, "max_epoch": 60 } }' \
    data/config/model.hybrid.jsonnet
Traceback (most recent call last):
  File "exp.py", line 34, in <module>
    from model.ensemble_model import EnsembleModel
ModuleNotFoundError: No module named 'model.ensemble_model'
```

Thank you.

Best regards,
Minami

**Comment by pcyin** [comment]
Hi Minami,

So sorry for the delay! This should be fixed in our upstream repo https://github.com/CMUSTRUDEL/DIRE. Sorry for the confusion. I will deprecate this repo soon. Thanks!

Best,
Pengcheng

**Comment by usaribbon** [comment]
Hello Pengcheng,

Thank you for your comment and new information!
I'll follow your upstream repo.
Thank you so much.

Best regards,
Minami

**Comment by pcyin** [comment]
You are welcome :)
